-- ==========================================
-- Administration Context
-- ==========================================

CREATE TABLE admin_steward
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                 VARCHAR(255) UNIQUE      NOT NULL,
    password              VARCHAR(255)             NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    force_password_change BOOLEAN                  NOT NULL DEFAULT FALSE
);

-- ==========================================
-- Audit Context
-- ==========================================

CREATE TABLE audit_audit
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email VARCHAR(255)             NOT NULL,
    action_type VARCHAR(255)             NOT NULL,
    status      VARCHAR(50),
    ip_address  VARCHAR(255),
    details     JSONB,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ==========================================
-- Organization Context
-- ==========================================

CREATE TABLE organization_organization
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) UNIQUE      NOT NULL,
    identity_format_regex   VARCHAR(255),
    lifecycle               VARCHAR(50)              NOT NULL,
    subscription_type       VARCHAR(50)              NOT NULL,
    subscription_expires_at TIMESTAMP WITH TIME ZONE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE organization_organizer
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id       BIGINT       NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    password              VARCHAR(255) NOT NULL,
    force_password_change BOOLEAN      NOT NULL DEFAULT FALSE,
    verification_token    VARCHAR(255),
    token_expiry_date     TIMESTAMP WITH TIME ZONE,
    enabled               BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_organizer_organization FOREIGN KEY (organization_id) REFERENCES organization_organization (id) ON DELETE CASCADE,
    CONSTRAINT uq_organizer_email UNIQUE (email)
);

CREATE TABLE organization_scanner
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id       BIGINT       NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    password              VARCHAR(255) NOT NULL,
    force_password_change BOOLEAN      NOT NULL DEFAULT TRUE,
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_scanner_organization FOREIGN KEY (organization_id) REFERENCES organization_organization (id) ON DELETE CASCADE,
    CONSTRAINT uq_scanner_email UNIQUE (email)
);

-- ==========================================
-- Event Context
-- ==========================================

CREATE TABLE event_event
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT                   NOT NULL,
    organizer_id         BIGINT,
    name                 VARCHAR(255)             NOT NULL,
    start_date           TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date             TIMESTAMP WITH TIME ZONE NOT NULL,
    grace_minutes_before INT                      NOT NULL,
    grace_minutes_after  INT                      NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_event_organizer FOREIGN KEY (organizer_id) REFERENCES organization_organizer (id) ON DELETE SET NULL
);

CREATE TABLE event_session
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      BIGINT                   NOT NULL,
    activity_name VARCHAR(255)             NOT NULL,
    target_time   TIMESTAMP WITH TIME ZONE NOT NULL,
    intent        VARCHAR(50)              NOT NULL,
    CONSTRAINT fk_session_event FOREIGN KEY (event_id) REFERENCES event_event (id) ON DELETE CASCADE
);

CREATE TABLE event_rosterentry
(
    event_id    BIGINT NOT NULL,
    attendee_id BIGINT NOT NULL,
    PRIMARY KEY (event_id, attendee_id),
    CONSTRAINT fk_roster_event FOREIGN KEY (event_id) REFERENCES event_event (id) ON DELETE CASCADE
);

-- ==========================================
-- Attendee Context
-- ==========================================

CREATE TABLE attendee_attribute
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL,
    name            VARCHAR(255) NOT NULL,
    type            VARCHAR(255) NOT NULL,
    options         JSONB,
    UNIQUE (organization_id, name)
);

CREATE TABLE attendee_attendee
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT                   NOT NULL,
    identity        VARCHAR(255)             NOT NULL,
    first_name      VARCHAR(255)             NOT NULL,
    last_name       VARCHAR(255)             NOT NULL,
    attributes      JSONB,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (organization_id, identity)
);

-- ==========================================
-- Capture Context
-- ==========================================

CREATE TABLE capture_entry
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_uuid           VARCHAR(36)              NOT NULL, -- Constraint in index below
    organization_id     BIGINT                   NOT NULL,
    event_id            BIGINT                   NOT NULL,
    session_id          BIGINT,
    attendee_id         BIGINT                   NOT NULL,
    scanner_id          BIGINT                   NOT NULL,
    scan_timestamp      TIMESTAMP WITH TIME ZONE NOT NULL,
    punctuality         VARCHAR(50)              NOT NULL,
    sync_timestamp      TIMESTAMP WITH TIME ZONE NOT NULL,

    snapshot_identity   VARCHAR(255),
    snapshot_first_name VARCHAR(255),
    snapshot_last_name  VARCHAR(255)
);

-- ==========================================
-- Analytics Context
-- ==========================================

CREATE TABLE analytics_attributebreakdown
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT       NOT NULL,
    attribute_name  VARCHAR(255) NOT NULL,
    attribute_value VARCHAR(255) NOT NULL,
    attendee_count  BIGINT       NOT NULL,
    UNIQUE (event_id, attribute_name, attribute_value)
);

CREATE TABLE analytics_organizationsummary
(
    organization_id BIGINT PRIMARY KEY,
    total_events    BIGINT NOT NULL DEFAULT 0,
    total_attendees BIGINT NOT NULL DEFAULT 0,
    total_scanners  BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE analytics_eventsummary
(
    event_id        BIGINT PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    event_name      VARCHAR(255),
    roster_count    BIGINT NOT NULL DEFAULT 0,
    entry_count     BIGINT NOT NULL DEFAULT 0
);

-- ==========================================
-- Notification Context
-- ==========================================

CREATE TABLE notification_notificationoutbox
(
    id              UUID PRIMARY KEY,
    event_type      VARCHAR(255)             NOT NULL,
    payload         JSONB                    NOT NULL,
    status          VARCHAR(50)              NOT NULL,
    retry_count     INT                      NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE capture_orphaned_entry
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_event_id BIGINT,
    organization_id   BIGINT,
    scan_uuid         VARCHAR(36)              NOT NULL,
    raw_payload       JSONB                    NOT NULL,
    failure_reason    VARCHAR(255),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ==========================================
-- Performance Indexes
-- ==========================================

-- Enforce Uniqueness on Scan UUID (Idempotency)
CREATE UNIQUE INDEX idx_capture_entry_scan_uuid ON capture_entry (scan_uuid);

-- Optimize Report Generation (Filtering by Event + Time)
CREATE INDEX idx_capture_entry_event_timestamp ON capture_entry (event_id, scan_timestamp DESC);

CREATE INDEX idx_capture_orphaned_entry_org ON capture_orphaned_entry (organization_id);

