-- ============================================================================
-- AttendEx Consolidated Schema (V1)
-- Includes: Core Domain, Modulith Infrastructure, Analytics Read Models,
-- and Performance Optimization Indexes (GIN/Trigram)
-- ============================================================================

-- 0. Enable extensions for fuzzy search performance
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ==========================================
-- 1. Administration Context
-- ==========================================

CREATE TABLE admin_steward
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                 VARCHAR(255) UNIQUE      NOT NULL,
    password              VARCHAR(255)             NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    force_password_change BOOLEAN                  NOT NULL DEFAULT FALSE
);

-- ==========================================
-- 2. Audit Context
-- ==========================================

CREATE TABLE audit_audit
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email VARCHAR(255)             NOT NULL,
    action_type VARCHAR(255)             NOT NULL,
    status      VARCHAR(50),
    ip_address  VARCHAR(255),
    details     JSONB,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ==========================================
-- 3. Organization Context
-- ==========================================

CREATE TABLE organization_organization
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) UNIQUE      NOT NULL,
    identity_format_regex   VARCHAR(255),
    lifecycle               VARCHAR(50)              NOT NULL,
    subscription_type       VARCHAR(50)              NOT NULL,
    subscription_expires_at TIMESTAMP WITH TIME ZONE,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE organization_organizer
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id       BIGINT       NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    password              VARCHAR(255) NOT NULL,
    force_password_change BOOLEAN      NOT NULL DEFAULT FALSE,
    verification_token    VARCHAR(255),
    token_expiry_date     TIMESTAMP WITH TIME ZONE,
    enabled               BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_organizer_organization FOREIGN KEY (organization_id) REFERENCES organization_organization (id) ON DELETE CASCADE,
    CONSTRAINT uq_organizer_email UNIQUE (email)
);

CREATE TABLE organization_scanner
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id       BIGINT       NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    password              VARCHAR(255) NOT NULL,
    force_password_change BOOLEAN      NOT NULL DEFAULT TRUE,
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_scanner_organization FOREIGN KEY (organization_id) REFERENCES organization_organization (id) ON DELETE CASCADE,
    CONSTRAINT uq_scanner_email UNIQUE (email)
);

-- ==========================================
-- 4. Event Context
-- ==========================================

CREATE TABLE event_event
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT                   NOT NULL,
    organizer_id         BIGINT,
    name                 VARCHAR(255)             NOT NULL,
    start_date           TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date             TIMESTAMP WITH TIME ZONE NOT NULL,
    grace_minutes_before INT                      NOT NULL,
    grace_minutes_after  INT                      NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_event_organizer FOREIGN KEY (organizer_id) REFERENCES organization_organizer (id) ON DELETE SET NULL
);

CREATE TABLE event_session
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      BIGINT                   NOT NULL,
    activity_name VARCHAR(255)             NOT NULL,
    target_time   TIMESTAMP WITH TIME ZONE NOT NULL,
    intent        VARCHAR(50)              NOT NULL,
    CONSTRAINT fk_session_event FOREIGN KEY (event_id) REFERENCES event_event (id) ON DELETE CASCADE
);

CREATE TABLE event_roster_entry
(
    event_id    BIGINT NOT NULL,
    attendee_id BIGINT NOT NULL,
    PRIMARY KEY (event_id, attendee_id),
    CONSTRAINT fk_roster_event FOREIGN KEY (event_id) REFERENCES event_event (id) ON DELETE CASCADE
);

-- ==========================================
-- 5. Attendee Context
-- ==========================================

CREATE TABLE attendee_attribute
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL,
    name            VARCHAR(255) NOT NULL,
    type            VARCHAR(255) NOT NULL,
    options         JSONB,
    UNIQUE (organization_id, name)
);

CREATE TABLE attendee_attendee
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT                   NOT NULL,
    identity        VARCHAR(255)             NOT NULL,
    first_name      VARCHAR(255)             NOT NULL,
    last_name       VARCHAR(255)             NOT NULL,
    attributes      JSONB,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at      TIMESTAMP WITH TIME ZONE
);

-- Partial Index: Ensure identity is unique per organization ONLY for active (non-deleted) attendees
CREATE UNIQUE INDEX idx_attendee_org_identity_active
    ON attendee_attendee (organization_id, identity) WHERE deleted_at IS NULL;

-- ==========================================
-- 6. Capture Context
-- ==========================================

CREATE TABLE capture_entry
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_uuid           VARCHAR(36)              NOT NULL,
    organization_id     BIGINT                   NOT NULL,
    event_id            BIGINT                   NOT NULL,
    session_id          BIGINT,
    attendee_id         BIGINT                   NOT NULL,
    scanner_id          BIGINT                   NOT NULL,
    scan_timestamp      TIMESTAMP WITH TIME ZONE NOT NULL,
    punctuality         VARCHAR(50)              NOT NULL,
    sync_timestamp      TIMESTAMP WITH TIME ZONE NOT NULL,

    snapshot_identity   TEXT,
    snapshot_first_name TEXT,
    snapshot_last_name  TEXT,
    snapshot_attributes JSONB
);

CREATE TABLE capture_orphaned_entry
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_event_id BIGINT,
    organization_id   BIGINT,
    scan_uuid         VARCHAR(36)              NOT NULL,
    raw_payload       JSONB                    NOT NULL,
    failure_reason    VARCHAR(255),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ==========================================
-- 7. Analytics Context (Read Models)
-- ==========================================

CREATE TABLE analytics_attribute_breakdown
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT       NOT NULL,
    attribute_name  VARCHAR(255) NOT NULL,
    attribute_value VARCHAR(255) NOT NULL,
    attendee_count  BIGINT       NOT NULL,
    UNIQUE (event_id, attribute_name, attribute_value)
);

CREATE TABLE analytics_organization_summary
(
    organization_id BIGINT PRIMARY KEY,
    total_events    BIGINT NOT NULL DEFAULT 0,
    total_attendees BIGINT NOT NULL DEFAULT 0,
    total_scanners  BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE analytics_event_summary
(
    event_id        BIGINT PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    event_name      VARCHAR(255),
    roster_count    BIGINT NOT NULL DEFAULT 0,
    entry_count     BIGINT NOT NULL DEFAULT 0
);

-- NEW: Session Stats Read Model
CREATE TABLE analytics_session_summary
(
    session_id  BIGINT NOT NULL PRIMARY KEY,
    event_id    BIGINT NOT NULL,
    entry_count BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_analytics_session_event ON analytics_session_summary (event_id);

-- NEW: Scanner Stats Read Model
CREATE TABLE analytics_scanner_summary
(
    scanner_id  BIGINT NOT NULL PRIMARY KEY,
    event_id    BIGINT NOT NULL,
    entry_count BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_analytics_scanner_event ON analytics_scanner_summary (event_id);

-- ==========================================
-- 8. Notification Context
-- ==========================================

CREATE TABLE notification_notification_outbox
(
    id              UUID PRIMARY KEY,
    event_type      VARCHAR(255)             NOT NULL,
    payload         JSONB                    NOT NULL,
    status          VARCHAR(50)              NOT NULL,
    retry_count     INT                      NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ==========================================
-- 9. Spring Modulith Infrastructure
-- ==========================================

CREATE TABLE event_publication
(
    id               UUID                     NOT NULL,
    event_type       VARCHAR(512)             NOT NULL,
    listener_id      VARCHAR(512)             NOT NULL,
    serialized_event TEXT                     NOT NULL,
    publication_date TIMESTAMP WITH TIME ZONE NOT NULL,
    completion_date  TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

CREATE INDEX idx_event_publication_completion_date ON event_publication (completion_date);

-- ==========================================
-- 10. Performance Indexes (B-Tree)
-- ==========================================

CREATE UNIQUE INDEX idx_capture_entry_scan_uuid ON capture_entry (scan_uuid);
CREATE INDEX idx_capture_entry_event_timestamp ON capture_entry (event_id, scan_timestamp DESC);
CREATE INDEX idx_capture_orphaned_entry_org ON capture_orphaned_entry (organization_id);
CREATE INDEX idx_event_event_deleted_at ON event_event (deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_attendee_attendee_deleted_at ON attendee_attendee (deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_event_event_organization_id ON event_event (organization_id);
CREATE INDEX idx_event_roster_entry_attendee_id ON event_roster_entry (attendee_id);
CREATE INDEX idx_capture_entry_session_id ON capture_entry (session_id);
CREATE INDEX idx_capture_entry_attendee_id ON capture_entry (attendee_id);
CREATE INDEX idx_capture_entry_scanner_id ON capture_entry (scanner_id);
CREATE INDEX idx_capture_entry_scan_timestamp_brin ON capture_entry USING BRIN (scan_timestamp);

-- ==========================================
-- 11. Performance Indexes (GIN / Trigram)
-- ==========================================
-- These enable ultra-fast substring matching (e.g. "LIKE '%query%'") for search

CREATE INDEX idx_attendee_identity_trgm ON attendee_attendee USING gin (identity gin_trgm_ops);
CREATE INDEX idx_attendee_firstname_trgm ON attendee_attendee USING gin (first_name gin_trgm_ops);
CREATE INDEX idx_attendee_lastname_trgm ON attendee_attendee USING gin (last_name gin_trgm_ops);

CREATE INDEX idx_entry_snapshot_identity_trgm ON capture_entry USING gin (snapshot_identity gin_trgm_ops);
CREATE INDEX idx_entry_snapshot_lastname_trgm ON capture_entry USING gin (snapshot_last_name gin_trgm_ops);
