CREATE TABLE admin_steward
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) UNIQUE      NOT NULL,
    password   VARCHAR(255)             NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE admin_audit
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email VARCHAR(255)             NOT NULL,
    action_type VARCHAR(255)             NOT NULL,
    details     JSONB,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE organization_organization
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) UNIQUE NOT NULL,
    identity_format_regex   VARCHAR(255),
    lifecycle               VARCHAR(50)         NOT NULL,
    subscription_type       VARCHAR(50)         NOT NULL,
    subscription_expires_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE organization_organizer
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id       BIGINT       NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    password              VARCHAR(255) NOT NULL,
    force_password_change BOOLEAN      NOT NULL DEFAULT FALSE,
    verification_token    VARCHAR(255),
    token_expiry_date     TIMESTAMP WITH TIME ZONE,
    enabled               BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_organizer_organization FOREIGN KEY (organization_id) REFERENCES organization_organization (id) ON DELETE CASCADE,
    UNIQUE (organization_id, email)
);

CREATE TABLE organization_scanner
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id       BIGINT       NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    password              VARCHAR(255) NOT NULL,
    force_password_change BOOLEAN      NOT NULL DEFAULT TRUE,
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_scanner_organization FOREIGN KEY (organization_id) REFERENCES organization_organization (id) ON DELETE CASCADE,
    UNIQUE (organization_id, email)
);

CREATE TABLE organization_attendee
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT                   NOT NULL,
    identity        VARCHAR(255)             NOT NULL,
    first_name      VARCHAR(255)             NOT NULL,
    last_name       VARCHAR(255)             NOT NULL,
    attributes      JSONB,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_attendee_organization FOREIGN KEY (organization_id) REFERENCES organization_organization (id) ON DELETE CASCADE,
    UNIQUE (organization_id, identity)
);

CREATE TABLE organization_event
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT                   NOT NULL,
    organizer_id         BIGINT                   NOT NULL,
    name                 VARCHAR(255)             NOT NULL,
    start_date           TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date             TIMESTAMP WITH TIME ZONE NOT NULL,
    grace_minutes_before INT                      NOT NULL,
    grace_minutes_after  INT                      NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_event_organization FOREIGN KEY (organization_id) REFERENCES organization_organization (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_organizer FOREIGN KEY (organizer_id) REFERENCES organization_organizer (id) ON DELETE SET NULL
);

CREATE TABLE organization_session
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      BIGINT                   NOT NULL,
    activity_name VARCHAR(255)             NOT NULL,
    target_time   TIMESTAMP WITH TIME ZONE NOT NULL,
    intent        VARCHAR(50)              NOT NULL,
    CONSTRAINT fk_session_event FOREIGN KEY (event_id) REFERENCES organization_event (id) ON DELETE CASCADE
);

CREATE TABLE organization_roster
(
    event_id     BIGINT              NOT NULL,
    attendee_id  BIGINT              NOT NULL,
    qr_code_hash VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (event_id, attendee_id),
    CONSTRAINT fk_roster_event FOREIGN KEY (event_id) REFERENCES organization_event (id) ON DELETE CASCADE,
    CONSTRAINT fk_roster_attendee FOREIGN KEY (attendee_id) REFERENCES organization_attendee (id) ON DELETE CASCADE
);

CREATE TABLE organization_attribute
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL,
    name            VARCHAR(255) NOT NULL,
    type            VARCHAR(255) NOT NULL,
    options         JSONB,
    CONSTRAINT fk_attribute_organization FOREIGN KEY (organization_id) REFERENCES organization_organization (id) ON DELETE CASCADE,
    UNIQUE (organization_id, name)
);

CREATE TABLE capture_entry
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id     BIGINT                   NOT NULL,
    attendee_id    BIGINT                   NOT NULL,
    scanner_id     BIGINT                   NOT NULL,
    scan_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    punctuality    VARCHAR(50)              NOT NULL,
    sync_timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE analytics_event_summary
(
    event_id             BIGINT PRIMARY KEY,
    event_name           VARCHAR(255),
    roster_count         INT DEFAULT 0,
    entry_count          INT DEFAULT 0,
    last_entry_timestamp TIMESTAMP WITH TIME ZONE
);
