spring.application.name=platform
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://[::1]:5432/attendex}
spring.datasource.username=${DB_USERNAME:attendex}
spring.datasource.password=${DB_PASSWORD:attendex}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.depends_on=flyway

spring.flyway.enabled=true
